version: '3.8'

services:
  app:
    image: webchat-swarm_webchat:latest
    environment:
      REDIS_HOST: redis_standalone 
      REDIS_PORT: 6379
    networks:
      - app_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8989:8989'
    depends_on:
      - redis_standalone  

networks:
  app_net:
    driver: overlay
    attachable: true 

volumes:
  redis-data: