version: '3.8'

services:
  webchat:
    image: mychatapp:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8989:8989"
    networks:
      - chatnet
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--appendonly", "yes"]
    networks:
      - chatnet
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  redis-data:

networks:
  chatnet:
    driver: overlay
