version: '3.8'

services:
  app:
    image: webchat-swarm_webchat:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - '8989:8989'
    init: true

  redis:
    image: redis:alpine
    networks:
      - app_net
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_net:
    driver: overlay

volumes:
  redis-data:
