version: '3.8'

services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--appendonly", "yes"]
    networks:
      - app_net
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: webchat-swarm_webchat:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_net
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '8989:8989'
    depends_on:
      - redis

networks:
  app_net:
    driver: overlay

volumes:
  redis-data: