version: '3.8'

services:
  app:
    image: webchat-swarm_webchat:latest
    environment:
      REDIS_HOST: tasks.redis
      REDIS_PORT: 6379
    networks:
      - app_net
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    ports:
      - '8989:8989'
    init: true

  redis:
    image: redis:alpine
    networks:
      - app_net
    volumes:
      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure


networks:
  app_net:
    driver: overlay

volumes:
  redis-data:
