version: '3.8'

services:
  webchat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--appendonly", "yes"]

    restart: unless-stopped

volumes:
  redis-data:
